### ISSUE TITLE
浏览器设置为Firefox时报错

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/phoenix.framework#17]
Exception in thread "main" java.lang.RuntimeException: Driver path is empty!
	at org.suren.autotest.web.framework.selenium.SeleniumEngine.loadDriverFromMapping(SeleniumEngine.java:449)
	at org.suren.autotest.web.framework.selenium.SeleniumEngine.loadDefaultEnginePath(SeleniumEngine.java:398)
	at org.suren.autotest.web.framework.selenium.SeleniumEngine.initConfig(SeleniumEngine.java:110)
	at org.suren.autotest.web.framework.selenium.SeleniumEngine.init(SeleniumEngine.java:129)

**Comment by LinuxSuRen** [comment]
已修正
